import NavBar from '@/components/NavBar';
import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Flex } from 'next/font/google';
import Footer from '@/components/Footer';

const roboto = Roboto_Flex({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
